version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017/orders
      KAFKA_BROKER: kafka:9092

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "3002:3001"
    depends_on:
      - kafka
      - mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017/inventory
      KAFKA_BROKER: kafka:9092
 